[package]
name = "osmviz"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.2"
reqwest = {version="0.13.1", features=["blocking", "deflate", "gzip"]}
mvt-reader = "2.2.0"
image = "0.25.9"
anyhow = "1.0.100"
vulkano-util = "0.35.0"
vulkano-shaders = "0.35.0"
glam = "0.30.10"
winit = "0.30.12"
lru = "0.16.3"
geojson = "0.24.2"
geozero = { version = "0.15.1", features=["with-mvt"] }
geo = "0.32.0"
egui_winit_vulkano = "0.28.0"
egui = "0.31"
log = "0.4.29"
env_logger = "0.11.8"
rayon = "1.11.0"

[profile.dev]
opt-level = 1
